name: 'crontab task'
on: 
  push:
    branches:
      - main
  schedule:
    # Beijing Time 01:00
    - cron: '0 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
          cache: 'pip'
      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 20
          max_attempts: 3
          retry_on: error
          command: |
            pip install -r requirements.txt
            pip install pytest-playwright
            playwright install chromium
            playwright install firefox
            playwright install-deps
      - name: Execute
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 20
          max_attempts: 6
          retry_on: error
          command: python main.py
      - name: Push
        run: |
          date "+%Y-%m-%d %H:%M:%S" >> actions.txt
          today=`date +"%Y-%m-%d"`
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[${today}] done"
          git push

